locals {
  # Values are set outside Terraform (AWS Console / CLI). Terraform only creates the secret slot.
  manual_secrets = {
    "DATABASE_URL" = {
      description = "PostgreSQL database connection URL"
    }
    "JWT_SECRET" = {
      description = "JWT secret for authentication"
    }
    "AWS_ACCESS_KEY_ID" = {
      description = "AWS access key for S3 and other services"
    }
    "AWS_SECRET_ACCESS_KEY" = {
      description = "AWS secret access key"
    }
    "SUPABASE_URL" = {
      description = "Supabase project URL"
    }
    "SUPABASE_PUBLISHABLE_KEY" = {
      description = "Supabase publishable API key"
    }
    "SUPABASE_SECRET_KEY" = {
      description = "Supabase secret API key"
    }
    "SUPABASE_JWT_SECRET" = {
      description = "Supabase JWT secret for token verification"
    }
    "HF_TOKEN" = {
      description = "HuggingFace API token"
    }
    "REDIS_URL" = {
      description = "Redis connection URL"
    }
  }

  # Values are set by Terraform itself (auto-generated or derived from variables).
  auto_secrets = {
    "REDIS_PASSWORD" = {
      description = "Redis requirepass password (auto-generated by Terraform)"
    }
    "REDIS_HOSTNAME" = {
      description = "sslip.io hostname derived from Elastic IP - used by certbot and HAProxy"
    }
    "CERTBOT_EMAIL" = {
      description = "Let's Encrypt contact email for certificate issuance"
    }
    "CELERY_BROKER_URL" = {
      description = "Public TLS broker URL used by App Runner to submit tasks to EC2 Celery"
    }
  }

  all_secrets = merge(local.manual_secrets, local.auto_secrets)
}

# Alphanumeric-only password so it embeds safely in a URL without percent-encoding.
resource "random_password" "redis" {
  length  = 32
  special = false
}

resource "aws_secretsmanager_secret" "evalhub" {
  for_each = local.all_secrets

  name        = "evalhub/${each.key}"
  description = each.value.description

  tags = {
    Name        = "evalhub/${each.key}"
    Project     = "evalhub"
    ManagedBy   = "terraform"
    Environment = "production"
  }
}

# Manually-set secrets start with PLACEHOLDER; the real value is set outside Terraform.
# Keep the original resource name "evalhub" so existing secret versions in state are
# not destroyed and recreated (which would overwrite real values with PLACEHOLDER).
resource "aws_secretsmanager_secret_version" "evalhub" {
  for_each = local.manual_secrets

  secret_id     = aws_secretsmanager_secret.evalhub[each.key].id
  secret_string = "PLACEHOLDER"

  lifecycle {
    ignore_changes = [secret_string]
  }
}

# REDIS_PASSWORD is auto-generated; Terraform owns and rotates the value.
resource "aws_secretsmanager_secret_version" "redis_password" {
  secret_id     = aws_secretsmanager_secret.evalhub["REDIS_PASSWORD"].id
  secret_string = random_password.redis.result
}

# REDIS_HOSTNAME and CERTBOT_EMAIL are set from Terraform inputs/locals.
resource "aws_secretsmanager_secret_version" "redis_config" {
  for_each = {
    REDIS_HOSTNAME = local.redis_hostname
    CERTBOT_EMAIL  = var.certbot_email
  }

  secret_id     = aws_secretsmanager_secret.evalhub[each.key].id
  secret_string = each.value
}

# CELERY_BROKER_URL is the public TLS endpoint App Runner uses to submit Celery tasks.
# Terraform computes it from the EIP hostname and the generated password so it's always
# in sync — no manual shell script step needed.
resource "aws_secretsmanager_secret_version" "celery_broker_url" {
  secret_id     = aws_secretsmanager_secret.evalhub["CELERY_BROKER_URL"].id
  secret_string = "rediss://:${random_password.redis.result}@${local.redis_hostname}:6380/0"
}
